version: '3.8'

services:

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs

  kanboard:
    image: kanboard/kanboard:latest
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - kanboard_data:/var/www/app/data
     - kanboard_plugins:/var/www/app/plugins
     - kanboard_ssl:/etc/nginx/ssl

  gogs:
    image: gogs/gogs:latest
    volumes:
      - ./gogs:/data
    ports:
      - "222:22"
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql
      
  drone-server:
    image: drone/drone:0.8
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - ./drone:/var/lib/drone/
    depends_on: 
      - gogs
      - mysql
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone-server:8000
      - DRONE_GOGS_URL=http://gogs:3000
      - DRONE_DEBUG=true
      - DRONE_SECRET=ALQU2M0KdptXUdTPKcEw
      - DRONE_GOGS=true
      - DRONE_GOGS_SKIP_VERIFY=false
      - DRONE_GOGS_PRIVATE_MODE=true

  drone-agent:
    image: drone/agent:0.8
    command: agent
    restart: always    
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=ALQU2M0KdptXUdTPKcEw
      - DRONE_DEBUG=true

volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local
  drone-server-data:
